westerny_project/urls.py
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.views.static import serve
from westerny_app.views import IndexView, MoviesView, AddMovieView, GenresView, AddGenreView, PeopleView
from westerny_app.views import AddPersonView, GenreDetailsView, EditGenreView, DeleteGenreView
from westerny_app.views import RegisterView, LoginView, LogoutView, RulesView, MyPlaceView, SearchMovieView
from westerny_app.views import SearchPersonView, StatsView, VerificationView, WaitingGenresView
from westerny_app.views import AcceptGenreView, AddArticleGenreView, DeleteArticleGenreView
from westerny_app.views import WaitingPeopleView, PersonDetailsView, EditPersonView, AcceptPersonView
from westerny_app.views import AddArticlePersonView, DeleteArticlePersonView, DeletePersonView, WaitingMoviesView
from westerny_app.views import MovieDetailsView, DeleteMovieView, AcceptMovieView, AddArticleMovieView
from westerny_app.views import EditMovieView, DeleteArticleMovieView, AddActorMovieView, DeleteActorMovieView
from westerny_app.views import UserDetailsView, GivePromotionView, PromotionAsksView
from westerny_app.views import RequestPasswordResetEmail, CompletePasswordReset, AcceptArticlePersonView, AcceptArticleMovieView
from westerny_app.views import GiveEditPersonView, GiveEditMovieView, MyMoviesView, SearchMyMovieView, MyPeopleView
from westerny_app.views import SearchMyPersonView, MyGenresView, PeopleRankView, MoviesRankView
from westerny_app.views import AddWatchlistView, RemoveWatchlistView, WatchlistView, RatedMoviesView, RatedPeopleView
from westerny_app.views import MoviesNewestView, PeopleNewestView, AddedMoviesView, AddedPeopleView, AddedGenresView
from westerny_app.views import SoldiersView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('index/', IndexView.as_view(), name="index"),
    path('rules/', RulesView.as_view(), name="rules"),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('my_place/', MyPlaceView.as_view(), name='my-place'),
    path('my_movies/', MyMoviesView.as_view(), name='my-movies'),
    path('my_people/', MyPeopleView.as_view(), name='my-people'),
    path('my_genres/', MyGenresView.as_view(), name='my-genres'),
    path('rated_movies/', RatedMoviesView.as_view(), name='rated-movies'),
    path('rated_people/', RatedPeopleView.as_view(), name='rated-people'),
    path('user_details/<int:user_id>', UserDetailsView.as_view(), name="user-details"),
    path('added_movies/<int:soldier_id>', AddedMoviesView.as_view(), name="added-movies"),
    path('added_people/<int:soldier_id>', AddedPeopleView.as_view(), name="added-people"),
    path('added_genres/<int:soldier_id>', AddedGenresView.as_view(), name="added-genres"),
    path('give_promotion/<int:soldier_id>', GivePromotionView.as_view(), name="give-promotion"),
    path('promotion_asks/', PromotionAsksView.as_view(), name="promotion-asks"),
    path('stats/', StatsView.as_view(), name='stats'),
    path('movies/', MoviesView.as_view(), name="movies"),
    path('movies_newest/', MoviesNewestView.as_view(), name="movies-newest"),
    path('search_movie/', SearchMovieView.as_view(), name="search-movie"),
    path('search_my_movie/', SearchMyMovieView.as_view(), name="search-my-movie"),
    path('movies_rank/', MoviesRankView.as_view(), name="movies-rank"),
    path('add_movie/', AddMovieView.as_view(), name="add-movie"),
    path('movie_details/<int:movie_id>', MovieDetailsView.as_view(), name="movie-details"),
    path('edit_movie/<int:movie_id>', EditMovieView.as_view(), name="edit-movie"),
    path('delete_movie/<int:movie_id>', DeleteMovieView.as_view(), name="delete-movie"),
    path('accept_movie/<int:movie_id>', AcceptMovieView.as_view(), name="accept-movie"),
    path('waiting_movies/', WaitingMoviesView.as_view(), name="waiting-movies"),
    path('add_actor_movie/<int:movie_id>', AddActorMovieView.as_view(), name="add-actor-movie"),
    path('delete_actor_movie/<int:movie_id>/<int:person_id>', DeleteActorMovieView.as_view(), name="delete-actor-movie"),
    path('gitve_edit_movie/<int:movie_id>/<int:soldier_id>', GiveEditMovieView.as_view(), name="give-edit-movie"),
    path('genres/', GenresView.as_view(), name="genres"),
    path('add_genre/', AddGenreView.as_view(), name="add-genre"),
    path('genre_details/<int:genre_id>', GenreDetailsView.as_view(), name="genre-details"),
    path('edit_genre/<int:genre_id>', EditGenreView.as_view(), name="edit-genre"),
    path('delete_genre/<int:genre_id>', DeleteGenreView.as_view(), name="delete-genre"),
    path('waiting_genres/', WaitingGenresView.as_view(), name="waiting-genres"),
    path('accept_genre/<int:genre_id>', AcceptGenreView.as_view(), name="accept-genre"),
    path('people/', PeopleView.as_view(), name="people"),
    path('people_newest/', PeopleNewestView.as_view(), name="people-newest"),
    path('add_person/', AddPersonView.as_view(), name="add-person"),
    path('person_details/<int:person_id>', PersonDetailsView.as_view(), name="person-details"),
    path('edit_person/<int:person_id>', EditPersonView.as_view(), name="edit-person"),
    path('delete_person/<int:person_id>', DeletePersonView.as_view(), name="delete-person"),
    path('waiting_people/', WaitingPeopleView.as_view(), name="waiting-people"),
    path('accept_person/<int:person_id>', AcceptPersonView.as_view(), name="accept-person"),
    path('search_person/', SearchPersonView.as_view(), name="search-person"),
    path('search_my_person/', SearchMyPersonView.as_view(), name="search-my-person"),
    path('people_rank/', PeopleRankView.as_view(), name="people-rank"),
    path('give_edit_person/<int:person_id>/<int:soldier_id>', GiveEditPersonView.as_view(), name="give-edit-person"),
    path('add_article_genre/<int:genre_id>', AddArticleGenreView.as_view(), name="add-article-genre"),
    path('delete_article_genre/<int:genre_id>/<int:article_id>', DeleteArticleGenreView.as_view(), name="delete-article-genre"),
    path('add_article_person/<int:person_id>', AddArticlePersonView.as_view(), name="add-article-person"),
    path('delete_article_person/<int:person_id>/<int:article_id>', DeleteArticlePersonView.as_view(), name="delete-article-person"),
    path('accept_article_person/<int:person_id>/<int:article_id>', AcceptArticlePersonView.as_view(), name="accept-article-person"),
    path('add_article_movie/<int:movie_id>', AddArticleMovieView.as_view(), name="add-article-movie"),
    path('delete_article_movie/<int:movie_id>/<int:article_id>', DeleteArticleMovieView.as_view(), name="delete-article-movie"),
    path('accept_article_movie/<int:movie_id>/<int:article_id>', AcceptArticleMovieView.as_view(), name="accept-article-movie"),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name="activate"),
    path('add_watchlist/<int:movie_id>', AddWatchlistView.as_view(), name="add-watchlist"),
    path('add_removelist/<int:movie_id>', RemoveWatchlistView.as_view(), name="remove-watchlist"),
    path('watchlist/', WatchlistView.as_view(), name="watchlist"),
    path('soldiers/', SoldiersView.as_view(), name="soldiers"),

    path('reset_password/', RequestPasswordResetEmail.as_view(), name='reset-password'),
    path('set_new_password/<uidb64>/<token>', CompletePasswordReset.as_view(), name="set-new-password"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

westerny_app/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from datetime import timezone, date, timedelta


class Counter(models.Model):
    counter = models.IntegerField()


class Rank(models.Model):
    name = models.CharField(max_length=32, unique=True)


class UserRank(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.DO_NOTHING)
    rank = models.ForeignKey(Rank, null=False, default=1, on_delete=models.DO_NOTHING)
    promotion_ask = models.BooleanField(default=False)

    def __str__(self):
        if self.rank.name == "kawalerzysta":
            return "kawalerzysto"
        elif self.rank.name == "kapral":
            return "kapralu"
        elif self.rank.name == "sierżant":
            return "sierżancie"
        elif self.rank.name == "porucznik":
            return "poruczniku"
        elif self.rank.name == "kapitan":
            return "kapitanie"
        elif self.rank.name == "major":
            return "majorze"
        elif self.rank.name == "pułkownik":
            return "pułkowniku"
        elif self.rank.name == "generał":
            return "generale"
        elif self.rank.name == "gubernator":
            return "gubernatorze"


class Article(models.Model):
    article_name = models.CharField(max_length=128)
    author = models.CharField(max_length=64)
    article_added_by = models.ForeignKey(User, null=False, on_delete=models.DO_NOTHING)
    link = models.URLField(unique=True, null=False)
    is_accepted = models.BooleanField(default=False)


class Rating(models.Model):
    rating = models.IntegerField(unique=True, null=False)

    def __str__(self):
        return str(self.rating)


class Person(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    date_birth = models.DateField(null=True, default=None)
    date_death = models.DateField(null=True, default=None)
    person_rating = models.FloatField(null=True, max_length=5)
    person_image = models.ImageField(blank=True, null=True, upload_to="person_images/")
    person_description = models.TextField(null=True, max_length=1500)
    person_added_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="person_added")
    person_accepted_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="person_accepted")
    person_edited_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="person_edited")
    person_article = models.ManyToManyField(Article, default=None)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class PersonRating(models.Model):
    rating = models.ForeignKey(Rating, null=False, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, null=False, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, null=False, on_delete=models.DO_NOTHING)


class Genre(models.Model):
    name = models.CharField(max_length=64, unique=True)
    genre_image = models.ImageField(blank=True, null=True, upload_to="genre_images/")
    genre_description = models.TextField(null=True, max_length=1500)
    genre_added_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="genre_added")
    genre_accepted_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="genre_accepted")
    genre_edited_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="genre_edited")
    genre_article = models.ManyToManyField(Article, default=None)

    def __str__(self):
        return self.name


class Year(models.Model):
    year = models.CharField(null=False, unique=True, max_length=4)

    def __str__(self):
        return self.year


class Movie(models.Model):
    title = models.CharField(max_length=128, null=True)
    org_title = models.CharField(max_length=128, default=None, null=True)
    director = models.ManyToManyField(Person, related_name='director')
    screenplay = models.ManyToManyField(Person, related_name='screenplay')
    music = models.ManyToManyField(Person, related_name='music')
    cinema = models.ManyToManyField(Person, related_name='cinema', default=None)
    starring = models.ManyToManyField(Person, through="PersonMovie")
    year = models.ForeignKey(Year, null=False, on_delete=models.DO_NOTHING)
    movie_rating = models.FloatField(null=True, max_length=5)
    genre = models.ManyToManyField(Genre)
    movie_image = models.ImageField(blank=True, null=True, upload_to="movie_images/")
    movie_description = models.TextField(null=True, max_length=1500)
    movie_added_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="movie_added")
    movie_accepted_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="movie_accepted")
    movie_edited_by = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING, related_name="movie_edited")
    movie_article = models.ManyToManyField(Article, default=None)
    watchlist = models.ManyToManyField(User, default=None, related_name="watchlist")


class MovieRating(models.Model):
    rating = models.ForeignKey(Rating, null=False, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, null=False, on_delete=models.DO_NOTHING)
    movie = models.ForeignKey(Movie, null=False, on_delete=models.DO_NOTHING)


class PersonMovie(models.Model):
    role = models.CharField(max_length=128, null=True)
    role_rating = models.FloatField(null=True, max_length=4)
    persons = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    movies = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    personmovie_added_by = models.ForeignKey(User, null=False, default=1, on_delete=models.DO_NOTHING)


class Deleted(models.Model):
    added_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="added_by")
    deleted_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="deleted_by")

westerny_app/templates/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}

    <div class="d-flex flex-row justify-content-around flex-wrap">
        <a class="btn btn-primary btn-lg guzik" href="{% url 'index' %}">STRONA GŁÓWNA</a>
    </div>
    <hr>
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h2 class="display-5 align-self-center header2"><i>Meldunek u kwatermistrza</i></h2>
    </div>
    <hr>
    {% if message %}
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="display-5 align-self-center header">
            {{ message }}
        </h3>
    </div>
    <hr>
    {% endif %}

    <form class="d-flex flex-column align-items-center" style="height: 100%; width: 100%;" action="{% url 'login' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" id="submit">Melduj się</button>
    </form>

    <span><a class="btn btn-link align-self-center" style="color: white;" href="{% url 'reset-password' %}">Resetuj hasło</a></span>
    <span><a class="btn btn-link align-self-center" style="color: white;" href="{% url 'register' %}">Rejestracja</a></span>
    <hr>


{% endblock %}

westerny_app/templates/movie_details.html
{% extends "base.html" %}
{% load static %}

{% block title %} Szczegóły Westernu {% endblock %}

{% block content %}

<div class="d-flex flex-column align-items-center" style="height: 100%; width: 100%;">
    <div class="d-flex flex-row justify-content-around flex-wrap">
        <a class="btn btn-primary btn-lg guzik" href="{% url 'index' %}">STRONA GŁÓWNA</a>
    </div>
    <div class="d-flex flex-row justify-content-around flex-wrap">
        <a class="btn btn-warning btn-lg guzik2" href="{% url 'movies' %}">WESTERNY</a>
        <a class="btn btn-warning btn-lg guzik2" href="{% url 'people' %}">LUDZIE</a>
        <a class="btn btn-warning btn-lg guzik2" href="{% url 'genres' %}">GATUNKI</a>

        <!-- {% if user.is_active %}
        <a class="btn btn-light btn-lg guzik2" href="{% url 'watchlist' %}">Moja Lista</a>
        {% endif %} -->
        {% if user.is_superuser or user.username == "Mariusz Czernic" or user.is_staff and not movie.movie_added_by.is_superuser or movie.movie_added_by == user and not movie.movie_edited_by.is_staff %}
        <a class="btn btn-success btn-lg guzik" href="{% url 'edit-movie' movie.id %}"> Edytuj Western</a>
        {% endif %}
        {% if user.is_superuser and user.username == "Westerny" or not movie.movie_accepted_by and user.is_staff %}
        <a class="btn btn-danger btn-lg guzik" href="{% url 'delete-movie' movie.id %}"> Usuń Western</a>
        {% endif %}
        {% if user.is_staff and not movie.movie_accepted_by %}
        <a class="btn btn-info btn-lg guzik" href="{% url 'accept-movie' movie.id %}"> Akceptuj</a>
        {% endif %}
        {% if user.is_superuser and not movie.movie_added_by.is_staff and movie.movie_edited_by.is_staff or user.is_staff and movie.movie_edited_by == user and not movie.movie_added_by.is_staff %}
        <a class="btn btn-info btn-lg guzik" href="{% url 'give-edit-movie' movie.id movie.movie_added_by.id %}"> Daj edycję</a>
        {% endif %}
    </div>

    {% if user.is_active and not user in movie.watchlist.all %}
    <div class="d-flex flex-row justify-content-center flex-wrap">
        <a class="btn btn-light btn-sm guzik3" href="{% url 'add-watchlist' movie.id %}">Dodaj do watchlisty</a>
    </div>
    {% endif %}
    {% if user.is_active and user in movie.watchlist.all %}
    <div class="d-flex flex-row justify-content-center flex-wrap">
        <a class="btn btn-dark btn-sm guzik4" href="{% url 'remove-watchlist' movie.id %}">Usuń z watchlisty</a>
    </div>
    {% endif %}

    <div class="d-flex flex-row justify-content-center align-items-center">
        <h2 class="display-5 align-self-center header2" style="margin-left: 3vh; margin-right: 3vh;">{{ movie.title }}</h2>
    </div>
    {% if movie.org_title %}
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="display-5 align-self-center header2" style="margin-left: 3vh; margin-right: 3vh;">(<i>{{ movie.org_title }})</i></h3>
    </div>
    {% endif %}

    <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        {% for genre in movie.genre.all|dictsort:"name" %}
        <a  class="btn btn-link align-self-center" href="{% url 'genre-details' genre.id %}" style="font-family: Georgia, serif; font-size: x-large; color: white; text-shadow: 2px 2px 1px black">{{ genre }} </a>
        {% endfor %}
    </div>

    {% if rating is not None %}
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="display-5 align-self-center header2" style="margin-left: 3vh; margin-right: 3vh;"><i>Ocena:</i> {{ rating }}/10 ({{len_movierating}} {% if len_movierating == 1 %}głos{% elif len_movierating > 1 and  4 >= len_movierating %}głosy{% else %}głosów{% endif %})</h3>
    </div>
    {% else %}
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="display-5 align-self-center header2" style="margin-left: 3vh; margin-right: 3vh;"><i>Brak ocen</i></h3>
    </div>
    {% endif %}
    {% if user.is_authenticated and user_rating is None %}
    <form class="d-flex flex-column align-items-center" style="height: 100%; width: 100%;" action="{% url 'movie-details' movie.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" id="submit">Dodaj Ocenę</button>
    </form>
    {% endif %}
    
    {% if movie.movie_image %}
    <div class="m-2">
      <img src="{{ movie.movie_image.url }}" alt="obraz {{ movie.title }}"
        width="380" class="img-thumbnail border border-secondary rounded-0">
    </div>
    {% else %}
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h4 class="display-5 align-self-center header">
            Brak zdjęcia.
        </h4>
    </div>
    <hr>
    {% endif %}

    <div class="d-flex flex-row justify-content-center align-items-center">
        <h4 class="display-5 align-self-center header">
            <i>Rok premiery:</i> {{ movie.year }}
        </h4>
    </div>
    <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        <h4 class="display-5 align-self-center header">
            <i>Reżyseria:</i>
        </h4>
        <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        {% for director in movie.director.all %}
        <a  class="btn btn-link align-self-center" href="{% url 'person-details' director.id %}" style="font-family: Georgia, serif; font-size: x-large; color: white; text-shadow: 2px 2px 1px black">{{ director }}</a>
        {% endfor %}
        </div>
    </div>

    {% if movie.screenplay.all.count > 0 %}
    <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        <h4 class="display-5 align-self-center header">
            <i>Scenariusz:</i>
        </h4>
        <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        {% for screenplay in movie.screenplay.all %}
        <a  class="btn btn-link align-self-center" href="{% url 'person-details' screenplay.id %}" style="font-family: Georgia, serif; font-size: x-large; color: white; text-shadow: 2px 2px 1px black">{{ screenplay }}</a>
        {% endfor %}
        </div>
    </div>
    {% endif %}

    {% if movie.music.all.count > 0 %}
    <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        <h4 class="display-5 align-self-center header">
            <i>Muzyka:</i>
        </h4>
        <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        {% for music in movie.music.all %}
        <a  class="btn btn-link align-self-center" href="{% url 'person-details' music.id %}" style="font-family: Georgia, serif; font-size: x-large; color: white; text-shadow: 2px 2px 1px black">{{ music }}</a>
        {% endfor %}
        </div>
    </div>
    {% endif %}

    {% if movie.cinema.all.count > 0 %}
    <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        <h4 class="display-5 align-self-center header">
            <i>Zdjęcia:</i>
        </h4>
        <div class="d-flex flex-row justify-content-center align-items-center flex-wrap">
        {% for cin in movie.cinema.all %}
        <a  class="btn btn-link align-self-center" href="{% url 'person-details' cin.id %}" style="font-family: Georgia, serif; font-size: x-large; color: white; text-shadow: 2px 2px 1px black">{{ cin }}</a>
        {% endfor %}
        </div>
    </div>
    {% endif %}

    {% if movie.movie_description %}
    <hr>
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="display-5 align-self-center header">
            <i>Opis Westernu</i>
        </h3>
    </div>
    <div>
        <h5 style="text-align: justify; margin-left: 3vh; margin-right: 3vh;" class="display-5 align-self-center header">
            {{ movie.movie_description }}
        </h5>
    </div>
    <hr>
    {% else %}
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h4 class="display-5 align-self-center header">
            Brak opisu.
        </h4>
    </div>
    <hr>
    {% endif %}

    {% if movie.personmovie_set.all.count > 0 %}
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="display-5 align-self-center header" style="margin-left: 3vh; margin-right: 3vh;">
            <i>Obsada</i>
        </h3>
    </div>

    <div class="d-flex flex-column justify-content-center align-items-center flex-wrap">
        {% for personmovie in movie.personmovie_set.all|dictsort:"id" %}
        <div class="d-flex flex-row justify-content-center align-items-center flex-wrap" style="margin-left: 3vh; margin-right: 3vh;">
            <a class="btn btn-link align-self-center" href="{% url 'person-details' personmovie.persons.id %}" style="font-family: Georgia, serif; font-size: x-large; color: white; text-shadow: 2px 2px 1px black">{{ personmovie.persons }}:</a>
            <h5 class="display-5 align-self-center header"><i>{{ personmovie.role }}</i></h5>
            {% if user.is_superuser or personmovie.personmovie_added_by == user or movie.movie_added_by == user and not movie.movie_edited_by.is_staff %}
            <span style="visibility: hidden;">.</span>
            <a class="btn btn-danger btn-sm guzik4" href="{% url 'delete-actor-movie' movie.id personmovie.persons.id %}">Usuń</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    {% if user.is_staff or movie.movie_added_by == user and not movie.movie_edited_by.is_staff %}
    <div class="d-flex flex-row justify-content-center flex-wrap">
        <a class="btn btn-success btn-sm guzik4" href="{% url 'add-actor-movie' movie.id %}">Dodaj aktora</a>
    </div>
    <hr>
    {% endif %}

    {% if articles.count > 0 %}
    <div class="d-flex flex-row justify-content-center align-items-center">
        <h3 class="display-5 align-self-center header" style="margin-left: 3vh; margin-right: 3vh;">
            <i>Artykuły o {{ movie.title }}</i>
        </h3>
    </div>

    <div class="d-flex flex-column justify-content-center align-items-center">
        {% for article in articles %}
        {% if user.is_staff or article.is_accepted %}
        <div class="d-flex flex-row justify-content-center align-items-center" style="margin-left: 3vh; margin-right: 3vh;">
            <a class="display-5 align-self-center header" href="{{ article.link }}" target="_blank" style="color: white;">{{ article.article_name }} - Autor: {{ article.author }}</a>
            {% if user.is_superuser or user.is_staff and not article.is_accepted or article.article_added_by == user and not movie.movie_edited_by or article.article_added_by == user and movie.movie_edited_by == user %}
            <span style="visibility: hidden;">..</span>
            <a class="btn btn-danger btn-sm guzik4" href="{% url 'delete-article-movie' movie.id article.id %}">Usuń</a>
            {% endif %}
            {% if user.is_staff and not article.is_accepted %}
            <span style="visibility: hidden;">..</span>
            <a class="btn btn-info btn-sm guzik4" href="{% url 'accept-article-movie' movie.id article.id %}">Akceptuj</a>
            {% endif %}
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    {% if user.is_staff or 3 > user_waiting_articles.count %}
    <div class="d-flex flex-row justify-content-center flex-wrap">
        <a class="btn btn-success btn-sm guzik4" href="{% url 'add-article-movie' movie.id %}">Dodaj link do artykułu</a>
    </div>
    {% endif %}

    <hr>
    <div class="d-flex flex-column align-items-center" style="height: 100%; width: 100%;">
        <span>Dodane przez: <a style="color: #dcdcc6;" href="{% url 'user-details' movie.movie_added_by.id %}">{{ movie.movie_added_by }}</a></span>
        {% if movie.movie_accepted_by %}<span>Zaakceptowane przez: <a style="color: #dcdcc6;" href="{% url 'user-details' movie.movie_accepted_by.id %}">{{ movie.movie_accepted_by }}</a></span>{% endif %}
        {% if movie.movie_edited_by %}<span>Ostatnia edycja: <a style="color: #dcdcc6;" href="{% url 'user-details' movie.movie_edited_by.id %}">{{ movie.movie_edited_by }}</a></span>{% endif %}
    </div>

</div>

{% endblock %}